package com.ljl.community.model;

import lombok.Data;

@Data
public class Article {
    private User user;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.TITLE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Long gtmCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Long gtmModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.CREATOR
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.TAG
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ARTICLE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.ID
     *
     * @return the value of ARTICLE.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.ID
     *
     * @param id the value for ARTICLE.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.TITLE
     *
     * @return the value of ARTICLE.TITLE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.TITLE
     *
     * @param title the value for ARTICLE.TITLE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.GTM_CREATE
     *
     * @return the value of ARTICLE.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Long getGtmCreate() {
        return gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.GTM_CREATE
     *
     * @param gtmCreate the value for ARTICLE.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setGtmCreate(Long gtmCreate) {
        this.gtmCreate = gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.GTM_MODIFIED
     *
     * @return the value of ARTICLE.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Long getGtmModified() {
        return gtmModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.GTM_MODIFIED
     *
     * @param gtmModified the value for ARTICLE.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setGtmModified(Long gtmModified) {
        this.gtmModified = gtmModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.CREATOR
     *
     * @return the value of ARTICLE.CREATOR
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.CREATOR
     *
     * @param creator the value for ARTICLE.CREATOR
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.COMMENT_COUNT
     *
     * @return the value of ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.COMMENT_COUNT
     *
     * @param commentCount the value for ARTICLE.COMMENT_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.VIEW_COUNT
     *
     * @return the value of ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.VIEW_COUNT
     *
     * @param viewCount the value for ARTICLE.VIEW_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.LIKE_COUNT
     *
     * @return the value of ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.LIKE_COUNT
     *
     * @param likeCount the value for ARTICLE.LIKE_COUNT
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.TAG
     *
     * @return the value of ARTICLE.TAG
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.TAG
     *
     * @param tag the value for ARTICLE.TAG
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ARTICLE.DESCRIPTION
     *
     * @return the value of ARTICLE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ARTICLE.DESCRIPTION
     *
     * @param description the value for ARTICLE.DESCRIPTION
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}