package com.ljl.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NAME
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.TOKEN
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Long gtmCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private Long gtmModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.DIO
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String dio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.AVATAR_URL
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    private String avatarUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ID
     *
     * @return the value of USER.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ID
     *
     * @param id the value for USER.ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ACCOUNT_ID
     *
     * @return the value of USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ACCOUNT_ID
     *
     * @param accountId the value for USER.ACCOUNT_ID
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.NAME
     *
     * @return the value of USER.NAME
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.NAME
     *
     * @param name the value for USER.NAME
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.TOKEN
     *
     * @return the value of USER.TOKEN
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.TOKEN
     *
     * @param token the value for USER.TOKEN
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.GTM_CREATE
     *
     * @return the value of USER.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Long getGtmCreate() {
        return gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.GTM_CREATE
     *
     * @param gtmCreate the value for USER.GTM_CREATE
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setGtmCreate(Long gtmCreate) {
        this.gtmCreate = gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.GTM_MODIFIED
     *
     * @return the value of USER.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public Long getGtmModified() {
        return gtmModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.GTM_MODIFIED
     *
     * @param gtmModified the value for USER.GTM_MODIFIED
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setGtmModified(Long gtmModified) {
        this.gtmModified = gtmModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.DIO
     *
     * @return the value of USER.DIO
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getDio() {
        return dio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.DIO
     *
     * @param dio the value for USER.DIO
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setDio(String dio) {
        this.dio = dio == null ? null : dio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.AVATAR_URL
     *
     * @return the value of USER.AVATAR_URL
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.AVATAR_URL
     *
     * @param avatarUrl the value for USER.AVATAR_URL
     *
     * @mbg.generated Sat Aug 10 13:10:39 CST 2019
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }
}